// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Suspension struct {
	Student string `json:"student"`
}

type Teacher struct {
	Teacher string `json:"teacher"`
	Student string `json:"student"`
}
